### ISSUE TITLE
Nailing Down the Cost

### ISSUE THREAD

**Issue by bhillmann** [knights-lab/analysis_SHOGUN#12]
The major objective of SHOGUN is to compete with 16S.

**Comment by danknights** [comment]
https://docs.google.com/spreadsheets/d/1uEMhvdU-Thiq-47gmuMr4_RPAzVCCLo3VC71U_wJRSU/edit?usp=drive_web

Dan

## 

Dan Knights, PhD
Assistant Professor
BioTechnology Institute, Computer Science and Engineering
University of Minnesota
http://www.knightslab.org
cell: 510-900-9015 (dials backwards)
office: MEMORIZE-PI (636-674-9374)
lab: 612-5-MICROB (612-564-2762)

On Tue, Nov 22, 2016 at 9:10 AM, Benjamin Hillmann <notifications@github.com
